[build]
	command = "eleventy"
	publish = "_site"
	functions = "functions"

[[redirect]]
	from = "/newuser"
	to = "/.netlify/functions/createUser"
	status = 200

[[redirect]]
	from = "/userdtl/*"
	to = "/.netlify/functions/showUser?id=:splat"
	status = 302
